using UnityEngine;

namespace Stationeers.ModdingHelpers
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Objects/Activate Button")]
#endif
    public class ActivateButton : global::ActivateButton
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
