using UnityEngine;

namespace Stationeers.ModdingHelpers
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Objects/Dial Knob")]
#endif
    public class DialKnob : Objects.DialKnob
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
