using DefaultNamespace;
using UnityEngine;

namespace Stationeers.ModdingHelpers
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Objects/SwitchMode")]
#endif
    public class SwitchMode : Objects.SwitchMode
    {
        // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
