using UnityEngine;

namespace Stationeers.ModdingHelpers
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Effects/Binary State Material Changer")]
#endif
    public class BinaryStateMaterialChanger : Effects.BinaryStateMaterialChanger
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
