using UnityEngine;

namespace Stationeers.ModdingHelpers
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Effects/Material Set Changer")]
#endif
    public class MaterialSetChanger : Effects.MaterialSetChanger
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
