using UnityEngine;

namespace Stationeers.ModdingHelpers
{
#if UNITY_EDITOR
    [AddComponentMenu("Stationeers/Objects/Pipes/Setting Wheel")]
#endif
    public class SettingWheel : Assets.Scripts.Objects.Pipes.SettingWheel
    {
      // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM CODE.
    }
}
